added smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -334,7 +334,7 @@ jobs:
   deploy-backend:
     docker:
       # Docker image here that supports Ansible
-      - image: cimg/node:13.8.0
+      - image: cimg/node:20.4.0
     steps:
       - checkout
       - install_awscli
@@ -379,28 +379,48 @@ jobs:
 
       # Here's where you will add some code to rollback on failure
 
-#   smoke-test:
-#     docker:
-#       # Lightweight Docker image 
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Get backend url
-#           command: |
-#             # your code here
-#       - run:
-#           name: Backend smoke test.
-#           command: |
-#             # your code here
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+  smoke-test:
+    docker:
+      - image: cimg/node:20.4.0
+    steps:
+      - checkout
+      - install_awscli
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            URL="http://udapeople-$CIRCLE_WORKFLOW_ID.s3-website-us-east-1.amazonaws.com/#/employees"
+            echo ${URL}
+            if curl -s ${URL} | grep "Welcome"
+            then
+              return 1
+            else
+              return 1
+            fi
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
+            # Fetch and prepare the BACKEND_IP env var
+            cd backend
+            export BACKEND_IP=$(aws ec2 describe-instances \
+              --filters Name=tag-value,Values="backend-${CIRCLE_WORKFLOW_ID}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+            export API_URL="http://${BACKEND_IP}:3030/api/status"
+            echo "$API_URL"
+            if curl ${API_URL} | grep "ok"
+            then
+                echo "success"
+                exit 0
+            else
+                echo "fail"
+                exit 1
+            fi
+      - destroy_environment
+      - revert-migrations
 
 #   cloudfront-update:
 #     docker:
